### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by STRML** [frz-dev/txmex#1]
Hi, I'm Samuel Reed, CTO of the [Bitcoin Mercantile Exchange (BitMEX)](https://www.bitmex.com).

We've been around since 2014 and we're one of the leading exchanges in the space.

It is likely that your project's name will cause significant confusion. Would you please consider changing it? For example, `BitTalk` appears not to be used by any major projects.

Thanks - we appreciate it!

**Comment by fed-franz** [comment]
Hi Samuel,

I understand. I will think of some other name.

Kind Regards,
Federico
